### ISSUE TITLE
Suggestion and bugs

### ISSUE THREAD

**Issue by aspectdev-ph** [mashwishi/Kohee#3]
Still null data in user info and bio is occurring:
![image](https://user-images.githubusercontent.com/32452006/209925178-e13b1c25-322f-4368-b082-b59b6400c1da.png)
Bio is overriden when ever i login using discord . IDK with other login method:
![image](https://user-images.githubusercontent.com/32452006/209925298-e744d5d7-2a4a-4893-aac0-6aa2ec4c5503.png)
More button text length:
![image](https://user-images.githubusercontent.com/32452006/209925398-f27cff34-bd50-48a3-8dff-a26ab56a55a9.png)

**Comment by aspectdev-ph** [comment]
add twitch, youtube on available list

**Comment by mashwishi** [comment]
**Issues:**
- Null objects on the card preview already fixed in version 1.2.6
- Bio issues, I will look into this issue and fix it soon as possible and this fix will also be included in version 1.2.7

**Suggestions:**
- Button text maxLength is currently set to 15, I will make it 30 on version 1.2.7
- I will add more social media soon, For now I will be add the suggested and also include some of the popular websites in 2022. This changes will also apply on version 1.2.7

**Comment by mashwishi** [comment]
**Patch Version 1.2.7 is now live!**

- More social media type
- Fixed bio issues
- Fixed Null objects
- Fixed Meta Tags
- Button Text set max to 30
